import type { Archetype } from '../types';

/**
 * 開放性が「閉じる」側に振れた 8 都市（内部 ID は L で始まる）。
 * すべてビルド時固定。実行時に生成・変更される値は一切含まない。
 */
export const CLOSED_SOCIETIES: readonly Archetype[] = [
  /* ================================================================
   * LFEC — 閉鎖 / 自由 / 拡張 / 集中
   * ============================================================== */
  {
    id: 'LFEC',
    cityName: '鉄華城市フェロニカ',
    cityReading: 'てっかじょうし・フェロニカ',
    title: '城壁の内なる巨人',
    tagline: '外に出る必要がないほど、内側を大きくした。',
    society:
      '外部との人の往来を最小限に絞り、その分の資源をすべて内側の巨大化に注いだ都市。壁の内では驚くほど自由で、誰が何を作っても、どこに住んでも咎められない。ただし成長の方向は都市中枢がひとつの図面で決めており、市民はその上で好きに振る舞う。百年で人口は増えていないのに、床面積は八倍になった。壁の高さと産業の熱気は、外の世界を必要としないという宣言そのものである。',
    visual: {
      palette: {
        skyTop: '#152b3d',
        skyMid: '#315a70',
        skyBottom: '#8ab8c5',
        sun: '#dff8ff',
        far: '#294858',
        mid: '#3d6676',
        near: '#193747',
        ground: '#142c38',
        accent: '#56b9d7',
        glow: '#36a6ca',
        fog: '#638b9a',
        foliage: '#527b6b',
      },
      skyline: {
        silhouette: 'ziggurat',
        density: 0.92,
        heightBias: 0.84,
        variance: 0.44,
        symmetry: 0.7,
        greenery: 0.08,
        signage: 0.62,
        patina: 0.74,
        antennae: 0.58,
      },
      landmarks: [
        {
          id: 'lfec-wall',
          name: '鉄華城壁',
          kind: 'greatWall',
          x: 0.5,
          depth: 0.14,
          scale: 1.3,
          note: '百年かけて七度嵩上げされた外壁。上に登る階段は内側にしかない。',
        },
        {
          id: 'lfec-tower',
          name: '城主塔',
          kind: 'megatower',
          x: 0.66,
          depth: 0.5,
          scale: 1.25,
          note: '拡張計画のすべてを描く中枢。図面は公開されるが、変更は受け付けない。',
        },
        {
          id: 'lfec-stack',
          name: '炉火の煙突',
          kind: 'reactorStack',
          x: 0.24,
          depth: 0.78,
          scale: 1.1,
          note: '内側だけで完結する製造の熱源。夜でも壁の内が赤く照らされる。',
        },
      ],
      lighting: {
        timeOfDay: 'dusk',
        intensity: 0.6,
        sunX: 0.08,
        sunY: 0.1,
        haze: 0.72,
        mood: '炉の照り返しで赤く濁った夕暮れ、壁の影がすべてを覆う',
      },
      weather: {
        kind: 'smog',
        density: 0.88,
        wind: 0.15,
        note: '排熱と粉塵が壁の内側に滞留し、空の色が季節を通じて変わらない。',
      },
    },
    causality: [
      {
        axis: 'openness',
        cause: '入域を厳しく管理したこと',
        effect: '嵩上げを繰り返した城壁が風景の主役になり、内と外の境が地形として見える。',
      },
      {
        axis: 'growth',
        cause: '規模の拡大に賭けたこと',
        effect: '壁の内側だけが段状に積み上がり、限られた面積に八倍の床が詰め込まれた。',
      },
      {
        axis: 'power',
        cause: '拡張計画を中枢に委ねたこと',
        effect: '段の高さと角度が全街区で揃い、ひとつの図面から起こされたことが一目でわかる。',
      },
      {
        axis: 'governance',
        cause: '内側の自由を守ったこと',
        effect: '整った段の上に、無許可の増築と個人の看板が雑然と貼り付いている。',
      },
    ],
    stats: [
      { label: '推定人口', value: '1,890万人' },
      { label: '外壁の高さ', value: '312m（七次嵩上げ）' },
      { label: '域外からの年間入域者', value: '4,100人' },
    ],
  },

  /* ================================================================
   * LFED — 閉鎖 / 自由 / 拡張 / 分散
   * ============================================================== */
  {
    id: 'LFED',
    cityName: '岩窟自由市グロッタ',
    cityReading: 'がんくつじゆうし・グロッタ',
    title: '境界の自営者',
    tagline: '外は信用しない。中央も信用しない。',
    society:
      '外部との関係を断ち、同時に中央の統治も拒んだ人々が、岩盤の空洞に掘り広げた都市。街区どころか一戸ごとに電源と水を持ち、必要な分だけ隣と融通する。掘削は止まらず、都市は毎年内側へ拡張していく。誰の許可も要らないので、坑道の交差点は設計上あり得ない角度で繋がっている。上位の権威が存在しないため、記録も統計もなく、都市の正確な広さを誰も知らない。',
    visual: {
      palette: {
        skyTop: '#0d1f31',
        skyMid: '#1f4056',
        skyBottom: '#496f7d',
        sun: '#afdce8',
        far: '#21394a',
        mid: '#315464',
        near: '#142b3a',
        ground: '#132733',
        accent: '#47b7d5',
        glow: '#35a6c5',
        fog: '#486d7b',
        foliage: '#477463',
      },
      skyline: {
        silhouette: 'lattice',
        density: 0.9,
        heightBias: 0.58,
        variance: 0.98,
        symmetry: 0.06,
        greenery: 0.14,
        signage: 0.66,
        patina: 0.95,
        antennae: 0.78,
      },
      landmarks: [
        {
          id: 'lfed-wall',
          name: '岩窟外壁',
          kind: 'greatWall',
          x: 0.5,
          depth: 0.1,
          scale: 1.2,
          note: '掘り残した岩盤そのものが壁。外へ通じる坑口は三つだけ。',
        },
        {
          id: 'lfed-market',
          name: '自営者の露店群',
          kind: 'stackedMarket',
          x: 0.3,
          depth: 0.8,
          scale: 1.2,
          note: '坑道の交差点に自然発生した市。同じ商品が十軒で違う値段で売られる。',
        },
        {
          id: 'lfed-antenna',
          name: '私設中継塔',
          kind: 'antennaForest',
          x: 0.76,
          depth: 0.55,
          scale: 0.95,
          note: '各戸が勝手に立てた通信塔。届く範囲は持ち主しか把握していない。',
        },
      ],
      lighting: {
        timeOfDay: 'night',
        intensity: 0.3,
        sunX: 0.5,
        sunY: 0.04,
        haze: 0.6,
        mood: '天窓から落ちるわずかな外光と、無数の裸電球が競り合う暗さ',
      },
      weather: {
        kind: 'dust',
        density: 0.85,
        wind: -0.2,
        note: '掘削の粉塵が絶えず舞い、光の筋がどこでも目に見える。',
      },
    },
    causality: [
      {
        axis: 'openness',
        cause: '外部との往来を断ったこと',
        effect: '都市が岩盤の内側だけへ拡張し、外へ通じる坑口が三つしか無い。',
      },
      {
        axis: 'power',
        cause: 'インフラを各戸で分散所有したこと',
        effect: '一戸ごとに発電機と水槽が突き出し、都市の壁面が設備の集積になっている。',
      },
      {
        axis: 'governance',
        cause: '記録と認証を拒んだこと',
        effect: '坑道が図面上あり得ない角度で交差し、正確な地図が存在しない。',
      },
      {
        axis: 'growth',
        cause: '拡張を止めなかったこと',
        effect: '掘削面が今も前進し、最前線の壁だけが常に新しい岩の色をしている。',
      },
    ],
    stats: [
      { label: '推定人口', value: '740万人（推定）' },
      { label: '確認された坑道総延長', value: '不明' },
      { label: '戸別電源保有率', value: '99%' },
    ],
  },

  /* ================================================================
   * LFGC — 閉鎖 / 自由 / 持続 / 集中
   * ============================================================== */
  {
    id: 'LFGC',
    cityName: '霧氷庭園都市フロスト・エデン',
    cityReading: 'むひょうていえんとし・フロスト・エデン',
    title: '閉じた園の設計者',
    tagline: '外の気候を諦め、内側にひとつだけ春を作った。',
    society:
      '外部の環境回復を早い段階で断念し、限られた資源を「内側の完璧な庭」に集中させた都市。円蓋の中は常春で、植生も水も百年前の設計どおりに循環している。暮らし方は自由で、行動の記録も取られない。ただし庭の設計と資源配分を一手に握るのは単一の設計機構で、その判断に市民が関与する回路は用意されなかった。外壁の外側には、諦められた気候がそのまま残っている。',
    visual: {
      palette: {
        skyTop: '#8fa8c0',
        skyMid: '#c3d3de',
        skyBottom: '#eef4f6',
        sun: '#f6fbff',
        far: '#9fb0bd',
        mid: '#b8c8d0',
        near: '#77899a',
        ground: '#cfdde3',
        accent: '#73d9df',
        glow: '#dff6ff',
        fog: '#e3edf2',
        foliage: '#5f9c74',
      },
      skyline: {
        silhouette: 'domes',
        density: 0.66,
        heightBias: 0.32,
        variance: 0.28,
        symmetry: 0.86,
        greenery: 0.9,
        signage: 0.1,
        patina: 0.16,
        antennae: 0.18,
      },
      landmarks: [
        {
          id: 'lfgc-dome',
          name: '霧氷温室〈フロスト・ドーム〉',
          kind: 'domeVault',
          x: 0.46,
          depth: 0.44,
          scale: 1.4,
          note: '常春を保つ主円蓋。設計変更は百年間一度も行われていない。',
        },
        {
          id: 'lfgc-terrace',
          name: '閉園の階段庭',
          kind: 'terraceGarden',
          x: 0.74,
          depth: 0.66,
          scale: 1.05,
          note: '円蓋の内壁に沿って登る庭。植える種は設計機構が指定する。',
        },
        {
          id: 'lfgc-wall',
          name: '境界の氷壁',
          kind: 'greatWall',
          x: 0.5,
          depth: 0.12,
          scale: 1.15,
          note: '円蓋の外側に築かれた断熱壁。向こう側の気温は表示されない。',
        },
      ],
      lighting: {
        timeOfDay: 'overcast',
        intensity: 0.66,
        sunX: 0.38,
        sunY: 0.7,
        haze: 0.62,
        mood: '乳白色の拡散光。円蓋の骨が空に薄い格子を落とす',
      },
      weather: {
        kind: 'snow',
        density: 0.7,
        wind: -0.12,
        note: '円蓋の外では雪が降り続き、内側からはそれが静かな景色として見える。',
      },
    },
    causality: [
      {
        axis: 'growth',
        cause: '循環と再生に投資を集めたこと',
        effect: '円蓋の内側が植生で満たされ、建物の高さが庭の日照で決まっている。',
      },
      {
        axis: 'openness',
        cause: '境界を引いて内側を守ったこと',
        effect: '断熱の壁が地平線を横切り、その外の景色が街のどこからも見えない。',
      },
      {
        axis: 'power',
        cause: '設計を単一の機構に委ねたこと',
        effect: '円蓋の骨組みが完全な同心円で、逸脱した構造が一箇所も無い。',
      },
      {
        axis: 'governance',
        cause: '暮らしの自由を残したこと',
        effect: '整った庭の区画ごとに、住人が勝手に足した小屋や温室が混じっている。',
      },
    ],
    stats: [
      { label: '推定人口', value: '530万人' },
      { label: '円蓋内の年較差', value: '4.1℃' },
      { label: '設計改訂回数', value: '0回' },
    ],
  },

  /* ================================================================
   * LFGD — 閉鎖 / 自由 / 持続 / 分散
   * ============================================================== */
  {
    id: 'LFGD',
    cityName: '苔生集落連環モスリング',
    cityReading: 'こけむすしゅうらくれんかん・モスリング',
    title: '自給の環をつなぐ者',
    tagline: '遠くとは繋がらない。隣とだけ、深く繋がる。',
    society:
      '広域の経済から降りることを選んだ集落が、環状に連なって残った都市。外部との交易はほとんど無く、必要なものは環の内側で作るか、諦める。中央の意思決定機関は無く、各集落が自分の水源と森を管理している。建物は古い骨組みを繰り返し補修したもので、苔と蔦が構造の一部として計算に入っている。誰も豊かではないが、百年前に建てた家がまだ使われている。',
    visual: {
      palette: {
        skyTop: '#8ea9a4',
        skyMid: '#bccec4',
        skyBottom: '#e8e6cf',
        sun: '#f6f2d8',
        far: '#7e9182',
        mid: '#6b8271',
        near: '#4a5f52',
        ground: '#546b47',
        accent: '#77cad5',
        glow: '#b6e4e5',
        fog: '#d3e0d6',
        foliage: '#3f7a45',
      },
      skyline: {
        silhouette: 'terraces',
        density: 0.54,
        heightBias: 0.2,
        variance: 0.66,
        symmetry: 0.12,
        greenery: 0.98,
        signage: 0.06,
        patina: 0.9,
        antennae: 0.12,
      },
      landmarks: [
        {
          id: 'lfgd-tree',
          name: '苔母樹',
          kind: 'worldTree',
          x: 0.54,
          depth: 0.5,
          scale: 1.15,
          note: '環の中心に残された最古の樹。どの集落もこの樹の水系に属している。',
        },
        {
          id: 'lfgd-terrace',
          name: '段々の苔田',
          kind: 'terraceGarden',
          x: 0.24,
          depth: 0.74,
          scale: 1.1,
          note: '斜面を刻んだ耕作段。境の石積みは集落ごとに積み方が違う。',
        },
        {
          id: 'lfgd-ring',
          name: '輪の集会所',
          kind: 'assemblyRing',
          x: 0.8,
          depth: 0.6,
          scale: 0.95,
          note: '環の集落が順に持ち回る会所。議事録は口伝で残される。',
        },
      ],
      lighting: {
        timeOfDay: 'dawn',
        intensity: 0.58,
        sunX: 0.22,
        sunY: 0.2,
        haze: 0.66,
        mood: '雨上がりの朝、谷に光の筋が差し込む数十分',
      },
      weather: {
        kind: 'rain',
        density: 0.62,
        wind: -0.15,
        note: '霧雨がよく降る。屋根の苔はそれを前提に厚みを設計されている。',
      },
    },
    causality: [
      {
        axis: 'growth',
        cause: '消費の上限を受け入れたこと',
        effect: '建物が高くなるのをやめ、百年前の骨組みが補修されて今も使われている。',
      },
      {
        axis: 'power',
        cause: '決定を集落ごとに置いたこと',
        effect: '石積みの積み方や屋根の勾配が集落ごとに違い、境界が造りで見分けられる。',
      },
      {
        axis: 'openness',
        cause: '外との交易を絞ったこと',
        effect: '環の外へ通じる道が細く、舗装が途中で途切れている。',
      },
      {
        axis: 'governance',
        cause: '記録を残さない自由を選んだこと',
        effect: '会所に台帳が無く、都市の決定の歴史が建物の増改築だけに残っている。',
      },
    ],
    stats: [
      { label: '推定人口', value: '96万人' },
      { label: '連環する集落数', value: '212集落' },
      { label: '食料自給率', value: '100%' },
    ],
  },

  /* ================================================================
   * LSEC — 閉鎖 / 統制 / 拡張 / 集中
   * ============================================================== */
  {
    id: 'LSEC',
    cityName: '単眼首都モノクル',
    cityReading: 'たんがんしゅと・モノクル',
    title: '唯一の意思の代行者',
    tagline: 'ひとつの意思が、ひとつの都市を、ひとつの形に整えた。',
    society:
      '外部を遮断し、内側の全情報を単一の中枢に集めることで、百年間ただ一度も方針が揺らがなかった都市。生産は右肩上がりに拡大し、街路は完全な格子に整えられ、市民の一日は分単位で最適化されている。異議を唱える回路は制度上存在せず、代わりにあらゆる不足も即座に解消される。都市は静かで清潔で、そしてすべての窓が同じ方向を向いている。',
    visual: {
      palette: {
        skyTop: '#172735',
        skyMid: '#354f60',
        skyBottom: '#718d99',
        sun: '#cbe7ed',
        far: '#2c4350',
        mid: '#405e6c',
        near: '#1b3340',
        ground: '#203743',
        accent: '#4eaecb',
        glow: '#79cfe0',
        fog: '#587786',
        foliage: '#466b5e',
      },
      skyline: {
        silhouette: 'megablock',
        density: 0.96,
        heightBias: 0.9,
        variance: 0.08,
        symmetry: 0.99,
        greenery: 0.04,
        signage: 0.34,
        patina: 0.1,
        antennae: 0.66,
      },
      landmarks: [
        {
          id: 'lsec-tower',
          name: '単眼庁',
          kind: 'megatower',
          x: 0.5,
          depth: 0.42,
          scale: 1.45,
          note: '都市のすべての決定が発せられる一点。他のどの建物もこれより高くない。',
        },
        {
          id: 'lsec-eye',
          name: '唯一の目',
          kind: 'watchEye',
          x: 0.5,
          depth: 0.72,
          scale: 1.2,
          note: '中枢の真下に据えられた観測装置。市民はこれと必ず正対して暮らす。',
        },
        {
          id: 'lsec-wall',
          name: '首都環壁',
          kind: 'greatWall',
          x: 0.5,
          depth: 0.12,
          scale: 1.25,
          note: '完全な円を描く外壁。門は一箇所のみで、開く時刻が決まっている。',
        },
      ],
      lighting: {
        timeOfDay: 'dusk',
        intensity: 0.44,
        sunX: 0.5,
        sunY: 0.12,
        haze: 0.78,
        mood: '灰に濁った赤い残光、影がすべて同じ角度に伸びる',
      },
      weather: {
        kind: 'ash',
        density: 0.9,
        wind: 0.06,
        note: '拡張の副産物である灰が絶えず降り、清掃は毎晩同じ時刻に行われる。',
      },
    },
    causality: [
      {
        axis: 'power',
        cause: '判断をひとつの中枢に集めたこと',
        effect: '街区が完全な格子に整い、中枢塔より高い建物がひとつも無い。',
      },
      {
        axis: 'governance',
        cause: '全域の可視化を選んだこと',
        effect: 'すべての窓が同じ方向を向き、視線の通らない路地が設計から消された。',
      },
      {
        axis: 'openness',
        cause: '外部を遮断したこと',
        effect: '外壁が完全な円を描き、門が一箇所しか開いていない。',
      },
      {
        axis: 'growth',
        cause: '供給の拡大を続けたこと',
        effect: '生産の灰が空を覆い、街の色が季節を通じて灰と赤のままである。',
      },
    ],
    stats: [
      { label: '推定人口', value: '5,410万人' },
      { label: '街路の格子誤差', value: '±0.2°' },
      { label: '方針変更（過去100年）', value: '0回' },
    ],
  },

  /* ================================================================
   * LSED — 閉鎖 / 統制 / 拡張 / 分散
   * ============================================================== */
  {
    id: 'LSED',
    cityName: '区画都市セクター・ナイン',
    cityReading: 'くかくとし・セクター・ナイン',
    title: '区画の自警者',
    tagline: '九つの区画が、互いを見張りながら競って伸びた。',
    society:
      '外部を閉ざしたのち、内部が九つの区画に割れたまま固定された都市。中央政府は機能を失い、各区画が独自の警備網と配給と生産を持つ。区画どうしは交易するが、境の隔壁は決して開かない。互いの生産量が公開されているため競争は激しく、都市全体は拡大し続けている。市民はどの区画にいても記録され、区画を移るには申請から三年かかる。',
    visual: {
      palette: {
        skyTop: '#3a3f47',
        skyMid: '#5b636b',
        skyBottom: '#98a0a4',
        sun: '#cdd4d6',
        far: '#4e565e',
        mid: '#646d74',
        near: '#383e45',
        ground: '#4a5055',
        accent: '#5cb8d1',
        glow: '#a7dce9',
        fog: '#8b959c',
        foliage: '#57694f',
      },
      skyline: {
        silhouette: 'towers',
        density: 0.93,
        heightBias: 0.76,
        variance: 0.24,
        symmetry: 0.78,
        greenery: 0.1,
        signage: 0.44,
        patina: 0.5,
        antennae: 0.8,
      },
      landmarks: [
        {
          id: 'lsed-wall',
          name: '区画隔壁',
          kind: 'greatWall',
          x: 0.34,
          depth: 0.3,
          scale: 1.1,
          note: '九つの区画を隔てる内壁。開閉記録は百年間更新されていない。',
        },
        {
          id: 'lsed-eye',
          name: '第九区監視塔',
          kind: 'watchEye',
          x: 0.68,
          depth: 0.58,
          scale: 1.1,
          note: '区画が自前で建てた監視塔。隣の区画を向いている。',
        },
        {
          id: 'lsed-stack',
          name: '配給熱源塔',
          kind: 'reactorStack',
          x: 0.16,
          depth: 0.76,
          scale: 1.0,
          note: '区画ごとに一本ずつ立つ熱源。融通の交渉は毎年決裂する。',
        },
      ],
      lighting: {
        timeOfDay: 'overcast',
        intensity: 0.5,
        sunX: 0.6,
        sunY: 0.58,
        haze: 0.74,
        mood: '低い雲に閉ざされた昼、区画ごとに違う色の警備灯が滲む',
      },
      weather: {
        kind: 'smog',
        density: 0.8,
        wind: 0.24,
        note: '九本の熱源塔の排煙が混ざらないまま層をつくり、空が縞に見える。',
      },
    },
    causality: [
      {
        axis: 'power',
        cause: 'インフラを区画ごとに分けたこと',
        effect: '同じ役目の熱源塔が九本立ち、どれも隣とは繋がっていない。',
      },
      {
        axis: 'governance',
        cause: '安全のための監視を選んだこと',
        effect: '区画の境に監視塔が並び、そのすべてが内側ではなく隣を向いている。',
      },
      {
        axis: 'openness',
        cause: '外部を閉ざしたこと',
        effect: '外周の壁に門が無く、都市の輪郭が完全に閉じた線になっている。',
      },
      {
        axis: 'growth',
        cause: '競争的な拡大を続けたこと',
        effect: '同じ規格のタワーが区画ごとに競って伸び、高さが揃った段差を作っている。',
      },
    ],
    stats: [
      { label: '推定人口', value: '2,870万人' },
      { label: '区画数', value: '9区（固定）' },
      { label: '区画間移住の所要期間', value: '約3年' },
    ],
  },

  /* ================================================================
   * LSGC — 閉鎖 / 統制 / 持続 / 集中
   * ============================================================== */
  {
    id: 'LSGC',
    cityName: '終氷都クリオ・ヴォールト',
    cityReading: 'しゅうひょうと・クリオ・ヴォールト',
    title: '永久保存の管理人',
    tagline: '変わらないことを、百年かけて完成させた。',
    society:
      '拡張を放棄し、外部を閉ざし、残された資源を「失わないこと」だけに使い切った都市。あらゆる物資・記録・生物種は凍結保管され、消費は個人単位で厳密に割り当てられる。判断はすべて保存機構が下し、市民の生活は百年前とほぼ同じ手順で反復されている。夜は長く、灯りは必要な場所にしか点かない。この都市の目的は、繁栄ではなく、次の千年へ何も減らさずに引き渡すことである。',
    visual: {
      palette: {
        skyTop: '#0a1226',
        skyMid: '#123048',
        skyBottom: '#2f5f6e',
        sun: '#a8e6ff',
        far: '#1c2f42',
        mid: '#27435a',
        near: '#121e2e',
        ground: '#d6e8f0',
        accent: '#72d9ee',
        glow: '#a7eff7',
        fog: '#3d6478',
        foliage: '#4a7f6e',
      },
      skyline: {
        silhouette: 'spires',
        density: 0.5,
        heightBias: 0.6,
        variance: 0.3,
        symmetry: 0.9,
        greenery: 0.12,
        signage: 0.08,
        patina: 0.12,
        antennae: 0.34,
      },
      landmarks: [
        {
          id: 'lsgc-spire',
          name: '終氷尖塔',
          kind: 'iceSpire',
          x: 0.44,
          depth: 0.46,
          scale: 1.3,
          note: '保管庫の排熱を空へ逃がす氷結塔。表面の霜は決して融けない。',
        },
        {
          id: 'lsgc-vault',
          name: '永久保存庫',
          kind: 'domeVault',
          x: 0.68,
          depth: 0.66,
          scale: 1.15,
          note: '地下九層に及ぶ保管施設。開扉の権限は保存機構の三名のみが持つ。',
        },
        {
          id: 'lsgc-tether',
          name: '凍結昇降索',
          kind: 'orbitalTether',
          x: 0.2,
          depth: 0.24,
          scale: 0.85,
          note: '軌道上の予備保管環へ通じる索。百年で四度しか使われていない。',
        },
      ],
      lighting: {
        timeOfDay: 'night',
        intensity: 0.26,
        sunX: 0.3,
        sunY: 0.05,
        haze: 0.5,
        mood: '極夜の青、地平線のわずかな残光と天のオーロラだけが動く',
      },
      weather: {
        kind: 'aurora',
        density: 0.85,
        wind: 0.08,
        note: 'オーロラが常時観測される。市民はこれを唯一の「変化するもの」と呼ぶ。',
      },
    },
    causality: [
      {
        axis: 'growth',
        cause: '消費の総量に上限を定めたこと',
        effect: '灯りが必要な場所にしか点かず、街の大部分が夜のまま残されている。',
      },
      {
        axis: 'power',
        cause: '判断を保存機構に集めたこと',
        effect: '塔の配置が完全な対称を保ち、百年間ひとつも建て替えられていない。',
      },
      {
        axis: 'openness',
        cause: '外部を閉ざしたこと',
        effect: '軌道への索が街の端に一本だけ残り、稼働記録がほとんど空白である。',
      },
      {
        axis: 'governance',
        cause: '厳密な計測を受け入れたこと',
        effect: '窓の数と大きさが全戸で同一で、割り当てを超える開口部が存在しない。',
      },
    ],
    stats: [
      { label: '推定人口', value: '210万人' },
      { label: '保管された生物種', value: '1,940,000種' },
      { label: '年間の建て替え件数', value: '0件' },
    ],
  },

  /* ================================================================
   * LSGD — 閉鎖 / 統制 / 持続 / 分散
   * ============================================================== */
  {
    id: 'LSGD',
    cityName: '戒律村落都市ノルマリア',
    cityReading: 'かいりつそんらくとし・ノルマリア',
    title: '戒律を編む者',
    tagline: '掟が細かいほど、村は長く続くと信じられている。',
    society:
      '外部を拒み、拡張を諦め、その代わりに「暮らしの作法」を極限まで細かく定めた村落の集まり。中央政府は無く、戒律は各村の合議で決まり、破れば村中に知られる。作物の植え方から屋根の勾配まで規定されているため、村の景観は驚くほど整っている。ただし村ごとに戒律が違うので、隣の村へ行くと整い方の作法だけが変わる。人口は減り続けているが、誰もそれを問題として議題に上げない。',
    visual: {
      palette: {
        skyTop: '#c8d8e0',
        skyMid: '#e2ebee',
        skyBottom: '#f6f7f2',
        sun: '#ffffff',
        far: '#a8b0ad',
        mid: '#8e9a93',
        near: '#67736c',
        ground: '#e8eef0',
        accent: '#65b9c9',
        glow: '#c4e9eb',
        fog: '#e0e8ea',
        foliage: '#5c7a52',
      },
      skyline: {
        silhouette: 'mounds',
        density: 0.6,
        heightBias: 0.12,
        variance: 0.14,
        symmetry: 0.82,
        greenery: 0.62,
        signage: 0.05,
        patina: 0.4,
        antennae: 0.08,
      },
      landmarks: [
        {
          id: 'lsgd-ring',
          name: '戒律の円環',
          kind: 'assemblyRing',
          x: 0.5,
          depth: 0.72,
          scale: 1.25,
          note: '戒律を読み上げる石の円環。彫られた条項は年に数条ずつ増えていく。',
        },
        {
          id: 'lsgd-tree',
          name: '掟の御神木',
          kind: 'worldTree',
          x: 0.74,
          depth: 0.48,
          scale: 0.95,
          note: '村の中心に必ず一本植えられる樹。枝を切る手順まで定められている。',
        },
        {
          id: 'lsgd-wall',
          name: '村境の石垣',
          kind: 'greatWall',
          x: 0.5,
          depth: 0.16,
          scale: 1.0,
          note: '村と村を隔てる低い石垣。跨ぐことはできるが、跨がない作法がある。',
        },
      ],
      lighting: {
        timeOfDay: 'noon',
        intensity: 0.78,
        sunX: 0.5,
        sunY: 0.74,
        haze: 0.56,
        mood: '雪明かりの反射で影の薄い真昼、輪郭だけが際立つ',
      },
      weather: {
        kind: 'snow',
        density: 0.6,
        wind: -0.08,
        note: '雪は多いが、除雪の順路も戒律で定められているため道の形が毎年同じになる。',
      },
    },
    causality: [
      {
        axis: 'governance',
        cause: '作法の遵守を可視化に委ねたこと',
        effect: '屋根の勾配と向きが村内で完全に揃い、逸脱した一軒が見つからない。',
      },
      {
        axis: 'power',
        cause: '戒律を村ごとに決めたこと',
        effect: '石垣を越えると揃い方の作法が変わり、整った景観が村単位で切り替わる。',
      },
      {
        axis: 'growth',
        cause: '拡張を諦めたこと',
        effect: '建物が地面に低く伏せ、屋根のほとんどが畑と集水に使われている。',
      },
      {
        axis: 'openness',
        cause: '外を拒んだこと',
        effect: '村境の石垣に門が設けられず、道が石垣の手前で終わっている。',
      },
    ],
    stats: [
      { label: '推定人口', value: '58万人' },
      { label: '村落数', value: '340村' },
      { label: '現行の戒律条項数', value: '11,208条' },
    ],
  },
] as const;
